name: Accessibility Test

on:
  pull_request:

jobs:
  storybook-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build-storybook

      - name: Run a11y tests
        run: npx test-storybook --url http://localhost:6006
